### ISSUE TITLE
Not getting any video stream to DK2

### ISSUE THREAD

**Issue by dstavila** [OSVR/OSVR-Unity-Palace-Demo#2]
As described, I've downloaded Core shapshot **125-g7642085**, and OSVR-Oculus-Plugin-build63-v0.1-18-g6a3e9ab-with-core-v0.2-**125-g7642085-32bits**

Bellow is my **osvr_server_config.oculusrift.sample.json** that I pass to **osvr_server.exe**
'''
{
  "drivers": [
    {
      "plugin": "com_osvr_OculusRift",
      "driver": "OculusRift",
      "params": {
        "index": 0
      }
    }
  ],
  **"display": "displays/Oculus_Rift_DK2.json"**
}
''''

As a result, HMD tracking works, but no video stream.
Any suggestions?

**Comment by DuFF14** [comment]
I am using the same setup. Is this with the Unity editor or the downloaded executable? Did you copy com_osvr_OculusRift.dll to osvr-plugins-0 folder?

**Comment by dstavila** [comment]
Downloaded executable, and yes I've copied com_osvr_OculusRift.dll. On the link below is server init log output.

http://oi57.tinypic.com/2r6i2v8.jpg

**Comment by DuFF14** [comment]
Looks fine. I don't think the issue is OSVR related if tracking is working. If you run the Unity demo with the Rift off and OSVR server not running, do you see anything? Is the Rift connected as an extended or duplicated display?

**Comment by DuFF14** [comment]
"As a result, HMD tracking works, but no video stream." You tested this with the TrackerViewer utility? Are you seeing video on the monitor but not on the HMD?

**Comment by dstavila** [comment]
Rift display mode: Direct HMD Access.
So demo is running without OSVR server and disabled rift.

**Comment by dstavila** [comment]
When I'm enabling server, I see on monitor video that should be displayed in rift, but rift not displaying anything.

**Comment by DuFF14** [comment]
Put the Rift in extended mode. That should fix the issue.

**Comment by dstavila** [comment]
So, every project that uses OSVR and Rift should be running in Extended mode?

**Comment by DuFF14** [comment]
I think that's the case. Direct Mode requires building with the Oculus SDK at this point.

**Comment by dstavila** [comment]
Thank you.
