### ISSUE TITLE
Four Screen Game-Breaking Bug.

### ISSUE THREAD

**Issue by andrewaf1** [OSVR/OSVR-Unity-Palace-Demo#22]
I just received the HDK 1.3. Read the tutorial, connected it, server works fine, head tracking works fine BUT when I fire up the Palace Demo and put on the HMD I see four screens, all of which are sideways. I tried updating drivers and firmware but no luck. I get the feeling this is a universal problem for me, but it seems to show itself best on Palace Demo. Any suggestions?

**Comment by dixievr** [comment]
Hello,

Same issue here. We have a 1.3 HDK, first try works well but after some restart on the Palace Demo, we see 4 screens split by black lines. Also, the image is rotating on the right or left side slowly, seems like a drifting issue.
We tried restarted the computer, unplug / replug the usb and hdmi cables, as reinstall drivers and runtime but no luck.
Any idea too ? 1.3 HDK just receive 2 days ago...

**Comment by DuFF14** [comment]
Strange issue, can someone try another demo such as https://github.com/OSVR/Unity-VR-Samples/releases and see if it is also a problem there? 

Is it in DirectMode? What operating system? Screenshots?

**Comment by dixievr** [comment]
Hello,

Yes, the config file is set to DirectMode on Win7 64.
The bug is the same with the Palace Demo and the Unity VR Samples. In addition there is a color render problem, on the VR Samples the white background appear yellow in the HDK.

**Comment by dixievr** [comment]
Hello,

We have 2 HDK so today I try to test with the second one headset on the same belt and hardware connections, and It appear that is the Headset broken. Everything work well with the second one, no glitch - black lines or color issues.
I guess I have to check with the OSVR/Razer support. The 2 HDK have been received 6 days ago...

**Comment by DuFF14** [comment]
Yea, sounds like faulty hardware. If it doesn't go away soon, contact Razer support for your refund/replacement. I am closing this issue as it isn't isolated to the Palace Demo.
