### ISSUE TITLE
How To Run?

### ISSUE THREAD

**Issue by Balderick** [OSVR/OSVR-Unity-Palace-Demo#37]
The md readme doesn't give info on what to do with the zip file.  I can not find the .exe or see what i am supposed to do to launch the demo after extracting the .zip folder downloaded from this repos main page.

Having  older version osvr-palace-v0.6.5 i can see that directory contains three items with one being an exe.   Can i download the exe version of v0.6.9 demo? How do i compile the source to make the exe?  Do i need to do that?

How do i run palace demo nowadays on a windows machine?

**Comment by DuFF14** [comment]
The .exe is in the unzipped directory. Double-click the .exe to run it. The latest version is available at https://github.com/OSVR/OSVR-Unity-Palace-Demo/releases

You can build the project in Unity by going to File->Build.

**Comment by Balderick** [comment]
Yep it helps when i downloaded the right zip.  Thanks.
